name: Tests

on:
  push:
    paths:
      - package.json
      - index.js
      - .github/workflows/testrig.yml
      - action.yml
  pull_request:
    paths:
      - package.json
      - index.js
      - action.yml
  workflow_dispatch:

env:
  RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

jobs:
  example-secrets:
    name: Load demo encrypted .env.ci file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.x to mimic GHA prod environment
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install deps and test
        run: npm ci && npm run test
        id: dotenvx
        env:
          INPUT_KEY: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
          INPUT_INJECT_ENV_VARS: "true"
          INPUT_PATH: ".env.ci"
      - name: Check if everything's fine
        run: |
          echo 'Demo user: ${{ steps.dotenvx.outputs.DEMO_USER }}'
          echo 'Demo password (should be masked): ${{ steps.dotenvx.outputs.DEMO_PASS }}'
          echo 'Now touch ${{ steps.dotenvx.outputs.TOUCH }} (also blurred too)'
      - name: Check variables
        run: |
          printenv | grep DOTENV